version: '3.4'
services:
  db:
    container_name: db_trader
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password 
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: trader123
      MYSQL_USER: trader
      MYSQL_DATABASE: trader 
    networks:
      - trader-network
  
  trader_server:
    container_name: trader_server
    image: trader:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - trader-network

networks:
  trader-network:
    driver: bridge
